### ISSUE TITLE
Better list of games in archive

### ISSUE THREAD

**Issue by Alayan-stk-2** [coolchess123/tcecarchive#4]
First a picture : 
![TCEC_gui_archive](https://user-images.githubusercontent.com/25536748/57978214-cc741f00-7a08-11e9-8029-79265c6f1b8d.png)

I'm using recent Firefox.

There are three things which should be improved : 
1) A wider scroll bar. 1 or 2px wide scroll bar is almost unusable.
2) Use more vertical space. The space used is for 10 games, but when selecting more games per page it doesn't use the available additional vertical space.
3) Don't put the number of games/row and the selected row in the bottom of the scrollable area, where it's hidden until you actually scroll down. It should be always available in my opinion.

**Comment by coolchess123** [comment]
thanks
